const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.wrap,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Plugins.Mouse,
		C3.Behaviors.Follow,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Anchor,
		C3.Behaviors.Rotate,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Pin,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.ScriptsInEvents.EventoGameplay1_Event2_Act3,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.GoToLayout,
		C3.ScriptsInEvents.EventoGameplay1_Event9_Act2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.ScriptsInEvents.EventoGameplay1_Event20_Act2,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Anchor.Acts.SetEnabled,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{CenárioImaginado: 0},
	{Sólido: 0},
	{DarAVolta: 0},
	{lava: 0},
	{bloco: 0},
	{comida: 0},
	{player: 0},
	{tiro: 0},
	{corra: 0},
	{chapeu: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{Jogador: 0},
	{Senóide: 0},
	{blocoMovendo: 0},
	{Teclado: 0},
	{Áudio: 0},
	{txtVida: 0},
	{GameOver: 0},
	{PlayAgain: 0},
	{Mouse: 0},
	{Seguir: 0},
	{cano: 0},
	{Vida: 0},
	{ratão: 0},
	{vida: 0},
	{comecar: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{Cenario1: 0},
	{Cenario2: 0},
	{Cenario3: 0},
	{cedilha: 0},
	{ratomorte: 0},
	{telaInicial: 0},
	{certo: 0},
	{hat: 0},
	{zoio: 0},
	{txtPonto: 0},
	{dogpulo: 0},
	{hatake: 0},
	{dogqueda: 0},
	{s: 0},
	{dogseguivel: 0},
	{Âncora: 0},
	{caomonster: 0},
	{caonascer: 0},
	{mergulho1: 0},
	{Lava2: 0},
	{historia: 0},
	{back: 0},
	{Corra: 0},
	{corraescuro: 0},
	{moldura1: 0},
	{moldura2: 0},
	{moldura3: 0},
	{quadro1: 0},
	{quadro2: 0},
	{quadro3: 0},
	{quadro31: 0},
	{quadro311: 0},
	{moldura4: 0},
	{quadro4: 0},
	{quadro41: 0},
	{historia3dog: 0},
	{historia2: 0},
	{hisotirastar: 0},
	{carrgamento1: 0},
	{carrgamento2: 0},
	{carrgamentobar: 0},
	{carrgamentofndo: 0},
	{carrgamentocarg: 0},
	{Girar: 0},
	{carrgamentohat: 0},
	{carrgamentoblsack: 0},
	{ratcanoseguuir: 0},
	{MoverPara: 0},
	{gameplay2: 0},
	{gameplay21: 0},
	{lava21: 0},
	{Lava22: 0},
	{barrar: 0},
	{hatake2: 0},
	{hatake3: 0},
	{morcego2: 0},
	{awqui: 0},
	{Fixar: 0},
	{saida: 0},
	{saidareal: 0},
	{saidareal2: 0},
	{dogasegur: 0},
	{point: 0},
	{caomonster2: 0},
	{telavitoria: 0},
	{vitoria: 0},
	{vitoriaa: 0},
	{vioriapreta: 0},
	{telainiciotitle: 0},
	{vidas: 0},
	{ponto: 0}
];

self.InstanceType = {
	CenárioImaginado: class extends self.ITiledBackgroundInstance {},
	lava: class extends self.ISpriteInstance {},
	bloco: class extends self.ISpriteInstance {},
	comida: class extends self.ISpriteInstance {},
	Jogador: class extends self.ISpriteInstance {},
	blocoMovendo: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Áudio: class extends self.IInstance {},
	txtVida: class extends self.ITextInstance {},
	GameOver: class extends self.ISpriteFontInstance {},
	PlayAgain: class extends self.ISpriteFontInstance {},
	Mouse: class extends self.IInstance {},
	cano: class extends self.ISpriteInstance {},
	ratão: class extends self.ISpriteInstance {},
	vida: class extends self.ISpriteInstance {},
	comecar: class extends self.ISpriteInstance {},
	tiro: class extends self.ISpriteInstance {},
	Cenario1: class extends self.ISpriteInstance {},
	Cenario2: class extends self.ISpriteInstance {},
	Cenario3: class extends self.ISpriteInstance {},
	cedilha: class extends self.ISpriteInstance {},
	ratomorte: class extends self.ISpriteInstance {},
	telaInicial: class extends self.ISpriteInstance {},
	hat: class extends self.ISpriteInstance {},
	zoio: class extends self.ISpriteInstance {},
	txtPonto: class extends self.ITextInstance {},
	dogpulo: class extends self.ISpriteInstance {},
	hatake: class extends self.ISpriteInstance {},
	dogqueda: class extends self.ISpriteInstance {},
	dogseguivel: class extends self.ISpriteInstance {},
	caomonster: class extends self.ISpriteInstance {},
	caonascer: class extends self.ISpriteInstance {},
	mergulho1: class extends self.ISpriteInstance {},
	Lava2: class extends self.ISpriteInstance {},
	historia: class extends self.ITiledBackgroundInstance {},
	back: class extends self.ISpriteInstance {},
	Corra: class extends self.ISpriteInstance {},
	corraescuro: class extends self.ISpriteInstance {},
	moldura1: class extends self.ISpriteInstance {},
	moldura2: class extends self.ISpriteInstance {},
	moldura3: class extends self.ISpriteInstance {},
	quadro1: class extends self.ISpriteInstance {},
	quadro2: class extends self.ISpriteInstance {},
	quadro3: class extends self.ISpriteInstance {},
	quadro31: class extends self.ISpriteInstance {},
	quadro311: class extends self.ISpriteInstance {},
	moldura4: class extends self.ISpriteInstance {},
	quadro4: class extends self.ISpriteInstance {},
	quadro41: class extends self.ISpriteInstance {},
	historia3dog: class extends self.ISpriteInstance {},
	historia2: class extends self.ITiledBackgroundInstance {},
	hisotirastar: class extends self.ISpriteInstance {},
	carrgamento1: class extends self.ITiledBackgroundInstance {},
	carrgamento2: class extends self.ITiledBackgroundInstance {},
	carrgamentobar: class extends self.ISpriteInstance {},
	carrgamentofndo: class extends self.ISpriteInstance {},
	carrgamentocarg: class extends self.ISpriteInstance {},
	carrgamentohat: class extends self.ISpriteInstance {},
	carrgamentoblsack: class extends self.ISpriteInstance {},
	ratcanoseguuir: class extends self.ISpriteInstance {},
	gameplay2: class extends self.ISpriteInstance {},
	gameplay21: class extends self.ISpriteInstance {},
	lava21: class extends self.ISpriteInstance {},
	Lava22: class extends self.ISpriteInstance {},
	barrar: class extends self.ISpriteInstance {},
	hatake2: class extends self.ISpriteInstance {},
	hatake3: class extends self.ISpriteInstance {},
	morcego2: class extends self.ISpriteInstance {},
	awqui: class extends self.ISpriteInstance {},
	chapeu: class extends self.ISpriteInstance {},
	saida: class extends self.ISpriteInstance {},
	saidareal: class extends self.ISpriteInstance {},
	saidareal2: class extends self.ISpriteInstance {},
	dogasegur: class extends self.ISpriteInstance {},
	caomonster2: class extends self.ISpriteInstance {},
	telavitoria: class extends self.ISpriteInstance {},
	vitoria: class extends self.ISpriteInstance {},
	vitoriaa: class extends self.ISpriteInstance {},
	vioriapreta: class extends self.ISpriteInstance {},
	telainiciotitle: class extends self.ISpriteInstance {}
}